### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by CedricEugeni** [tid-kijyun/Kanna#113]
### Description:

I created an empty swift 3.0 project with `swift package init --type executable` command, then added dependency that is written in README.md file for Kanna.
Then I try to `swift build` but I have many compile errors :
`/Packages/Kanna-2.0.1/Sources/libxmlHTMLNode.swift:111:30: error: use of undeclared type 'htmlDocPtr'
    fileprivate var docPtr:  htmlDocPtr? = nil`
This one is the first one.
### Installation method:
- [ ] Carthage
- [ ] CocoaPods(1.1.0 or later)
- [ ] CocoaPods(older)
- [X] Manually
### Library version:
- [ ] v2.0.0
- [ ] v1.1.1
- [ ] v1.0.6
- [ ] v1.0.2
- [X] other: 2.0.1
### Xcode version:
- [X] 8.0 (Swift 3.0) 
- [ ] 8.0 (Swift 2.3)
- [ ] 7.3.1
- [ ] other: (Please fill in the version you are using.)

Am I doing something wrong ?

**Comment by jasef** [comment]
This is happening to me as well, it works if I open the Kanna project file in Xcode and compile (⌘+B), everything compiles fine, but running `swift build` produces the errors that are mentioned in the OP.

**Comment by foulkesjohn** [comment]
@tid-kijyun 2.0.2 doesn't seem to resolve this

**Comment by tid-kijyun** [comment]
I've released a new beta version 2.0.2. 

Please try to build using this command:

```
swift build -Xswiftc -DSPM
```

**Comment by foulkesjohn** [comment]
@tid-kijyun is there a way to include those flags when referencing the package in another project?

**Comment by noahemmet** [comment]
Getting similar errors to those above.

In Heroku (w/ Vapor and Swift 3.0.1):
```
<module-includes>:1:10: note: in file included from <module-includes>:1:
#include "/usr/include/libxml2/libxml/tree.h"
         ^
/usr/include/libxml2/libxml/tree.h:17:10: error: 'libxml/xmlversion.h' file not found
#include <libxml/xmlversion.h>
         ^
/tmp/build_ef4dea6a59374eac7aaaa106d64e96e4/My-App/Packages/Kanna-2.0.1/Sources/libxmlHTMLDocument.swift:29:12: error: could not build Objective-C module 'SwiftClibxml2'
    import SwiftClibxml2
```

and locally, in a new, otherwise-empty project:
```
note: you may be able to install libxml-2.0 using your system-packager:

    brew install libxml2

Compile Swift Module 'Kanna' (5 sources)
<module-includes>:1:9: note: in file included from <module-includes>:1:
#import "libxml2.h"
```

I've run and installed `brew install libxml2` locally, but the errors persist.

**Comment by foulkesjohn** [comment]
Its strange. I had it worked on one machine, then a few hours later tried again and got the above issues ^. I resolved it by adding `$(SDKROOT)/usr/include/libxml2` to header search paths in my Vapor project

**Comment by jasef** [comment]
@foulkesjohn can't find docs on how to add build flags to a dependency - where did you do it?

**Comment by foulkesjohn** [comment]
For a vapor project I ran `vapor xcode` which generates an xcode project to run. Then in the xcode project -> Select Kanna in target list -> build settings -> 'Header search paths' and add `$(SDKROOT)/usr/include/libxml2`. This probably isn't the best solution long term, but until Kanna works builds with SPM properly it meets my requirements

**Comment by jasef** [comment]
To be clear, @tid-kijyun, running `swift build -Xswiftc -DSPM` in my project's root directory with 2.0.2 compiles Kanna properly. Thanks for the fix!

**Comment by noahemmet** [comment]
Ah, to fix it I had to run 
```
brew install libxml2
brew link --force libxml2
```
I was omitting the second command when getting the above errors.

**Comment by tid-kijyun** [comment]
New version 2.1.0 does not require build options.

```
$ swift build
```

Thanks
