### ISSUE TITLE
Redefinition of module 'libxml2' in Xcode 9.3 beta iOS 11.3 beta

### ISSUE THREAD

**Issue by mcfans** [tid-kijyun/Kanna#176]
### Description:Redefinition of module 'libxml2' in Xcode 9.3 beta iOS 11.3 beta
<img width="989" alt="2018-01-26 11 40 49" src="https://user-images.githubusercontent.com/15027395/35424322-d36cfd98-028d-11e8-98b0-7fdbe1bc321a.png">

### Installation method:
- [ ] Carthage
- [x] CocoaPods
- [ ] Manually

### Library version:
- [ ] v2.0.0
- [ ] v1.1.0
- [ ] v1.0.2
- [x] other: (Please fill in the version you are using.)
feature 4.0
### Xcode version:
- [ ] 8.0 
- [ ] 7.3.1
- [x] other: (Please fill in the version you are using.)
Xcode9.3 beta

**Comment by Glagnar** [comment]
<img width="1644" alt="screen shot 2018-02-05 at 20 25 49" src="https://user-images.githubusercontent.com/5913559/35824315-c8b41986-0ab2-11e8-9436-baa0e622b5e4.png">

I get the same error, in Xcode 9.3

**Comment by mcfans** [comment]
@Glagnar try #177

**Comment by fantomnotabene** [comment]
Same here

**Comment by Glagnar** [comment]
@mcfans Thank you, this works - also in the newest Beta 2.

**Comment by MarekSlaninka** [comment]
Will it also be fixed in cocoapods version 4.0.0 ?

**Comment by mcfans** [comment]
Yes, it’s been merged

发自我的 iPad

**Comment by lemonkey** [comment]
FYI

`...Pods/Kanna/Sources/Kanna/CSS.swift:153:28: error: 'range(at:)' has been renamed to 'rangeAt(_:)'
        let range = result.range(at: at)`

**Comment by iwc** [comment]
The `error: 'range(at:)' has been renamed to 'rangeAt(_:)` issue is happening for me when I pull it in via Cocoapods, using latest git commit references don't work either. My toplevel project is building under swift 4.1.

**Comment by SunnyGit** [comment]
I still the same issues and I am running Swift 3.2. Is there something that I am missing here ?

**Comment by sathoeni** [comment]
@SunnyGit got the same error, i'm also building for swift 3.2 / 3.3

**Comment by SunnyGit** [comment]
Is it necessary to upgrade to Swift 4.0 ? Can some address this issue.

**Comment by tid-kijyun** [comment]
I am going to solve this issue. For now, using branch [feature/v3.0.0](https://github.com/tid-kijyun/Kanna/tree/feature/v3.0.0) may solve this issue.

**Comment by SunnyGit** [comment]
Thank you that helps.

**Comment by sathoeni** [comment]
Thanks, this branch works! 🎉

**Comment by o1xhack** [comment]
How could this been fixed if I'm using Swfit 3, with Kanna ~> 2.1.0???

**Comment by tid-kijyun** [comment]
I've just updated README.md.
@o1xhack For now, please use the `feature/v3.0.0` branch.

Note: I plan to release `3.0.0` this weekend.

**Comment by o1xhack** [comment]
@tid-kijyun Thanks, it now do not get that error. 

I'm using  `if let doc = Kanna.HTML(html: html, encoding: String.Encoding.utf8)`. But it give me the error after I do the feature branch. So I add `try?` and it becomes `if let doc = try? Kanna.HTML(html: html, encoding: String.Encoding.utf8)`.

But it still give me the error:

<img width="779" alt="2018-04-12 22 56 57" src="https://user-images.githubusercontent.com/10677990/38714558-d3e017d0-3ea4-11e8-9a72-12aed8f114a7.png">

**Comment by andrewtheis** [comment]
This error has returned on macOS Mojave / Xcode 10 betas.

**Comment by iDevPro** [comment]
redefinition on version 5.2.2 and Catalina + Xcode 11 :)
