### ISSUE TITLE
Version 5.2.0 with SPM gives libxml-2.0 warning with Xcode 11.4

### ISSUE THREAD

**Issue by ethanwa** [tid-kijyun/Kanna#231]
### Description:
The website says for version 5.2.0:

> We no longer need to install libxml2 using brew on Xcode 11.4 or later on macOS.

But in Xcode 11.4 (macOS  10.15.4) when I try to build with 5.2.0 using SPM, I get the following Warning:

`Package Loading: Resolve Package Graph: You may be able to install libxml-2.0 using your system package manager: brew install libxml2`

### Installation method:
- [ ] Carthage
- [ ] CocoaPods
- [x] Swift Package Manager
- [ ] Manually
- [ ] other: ()

**Comment by tid-kijyun** [comment]
@ethanwa Did you fail the build?

**Comment by tid-kijyun** [comment]
I've just released v5.2.1 which fixes this issue.

**Comment by ethanwa** [comment]
5.2.1 is now showing me this warning:

<img width="633" alt="Screen Shot 2020-03-26 at 3 56 20 AM" src="https://user-images.githubusercontent.com/1653780/77623099-e1b5b600-6f15-11ea-8230-12b5ea868d6d.png">

I did `brew install pkg-config` but the warning still appears for me.

**Comment by tid-kijyun** [comment]
Could you test using branch `feature/v5.2.2`?

**Comment by ethanwa** [comment]
That worked, thanks!!
